apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: cleanup
spec:
  steps:
    - name: cleanup
      image: alpine
      script: |
        #!/bin/sh
        echo "Cleaning up..."
        rm -rf /tmp/*

---
apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: nose-test
spec:
  params:
    - name: repo-url
      type: string
  steps:
    - name: run-tests
      image: python:3.10
      script: |
        pip install nose
        git clone $(params.repo-url) /src
        cd /src/app
        nosetests
